name: Run Newman Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Create reports directory
        run: mkdir -p newman-reports

      - name: Run Newman Tests
        run: |
          newman run postman/Freebe.postman_collection.json \
          --reporters cli,junit \
          --reporter-junit-export test-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: newman-reports/test-results.xml
