name: Qodana
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create code coverage folder if not exists
        run: |
          mkdir -p .qodana/code-coverage
        working-directory: ./

      - name: Run Tests
        run: ./gradlew test
        working-directory: ./

      - name: Archive coverage data
        uses: actions/upload-artifact@v3
        with:
          name: gradle-coverage-data-jacoco
          path: .qodana/code-coverage

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_965002036 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
